language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

script:
  - npm install create-elm-app -g
  - npm install
  - npm run test
  - npm run build

branches:
  only:
   - master