language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules
    - client/elm-stuff
    - sysconfcpus

sudo: required

install:
  - npm install create-elm-app -g
  - npm install

script:
  - npm run test
  - npm run build

branches:
  only:
   - master